include:
  - local: '.gitlab-ci/yml/global.yml'
  - local: '.gitlab-ci/yml/matrix.yml'
  - local: '.gitlab-ci/yml/metadata.yml'
  - local: '.gitlab-ci/yml/bootstrap.yml'
  - local: '.gitlab-ci/yml/build.yml'
  - local: '.gitlab-ci/yml/trigger-check.yml'
  - local: '.gitlab-ci/yml/pages.yml'

stages:
  - metadata
  - bootstrap
  - build
  - check
  - pages
