build:
  stage: build
  dependencies:
    - bootstrap
  script:
    - $SCRIPT_DIR/build.sh
  artifacts:
    paths:
      - gnulib/
    untracked: true
    expire_in: 1 week
    when: always
  extends: .target-platform-matrix
