default:
  image: quay.io/grub/debian-trixie-grub:2026-07-28.2

variables:
  SCRIPT_DIR: "./.gitlab-ci/script"

.artifacts:
  artifacts:
    paths:
      - gnulib/
    untracked: true
    expire_in: 1 week
    when: always

.check-artifacts:
  artifacts:
    untracked: true
    expire_in: 30 days
    when: always

.bootstrap:
  script:
    - ./bootstrap
  extends: .artifacts

.build:
  dependencies:
    - bootstrap
  script:
    - $SCRIPT_DIR/build.sh

.build-artifacts:
  extends:
    - .build
    - .artifacts

.build-clang:
  dependencies:
    - bootstrap
  script:
    - $SCRIPT_DIR/build-clang.sh

.check-before-script:
  before_script:
    - |
      if [ ! -e /dev/loop-control ]; then
        mknod -m 0660 /dev/loop-control c 10 237 || :
      fi
      for i in $(seq 0 64); do
        [ -e "/dev/loop$i" ] || mknod -m 0660 "/dev/loop$i" b 7 "$i" || :
      done
      if [ -e /etc/init.d/zfs-fuse ]; then
        /etc/init.d/zfs-fuse start || :
      fi

.check:
  script:
    - make --quiet TESTS=$TEST check
  dependencies:
    - build

.check-rerun-on-failure:
  script:
    - |
      if ! make --quiet TESTS=$TEST check; then
        strace -vf -tt -o $TEST.strace.log make --quiet TESTS=$TEST check;
      fi
  dependencies:
    - build
